name: thePRguy
favicon: null
layout_spectrum: 0.05153841967694461
typography_spectrum: 0.89357
title: Building Better Relationships Through Effective Communication
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005daa'
    - '#b9c5e4'
    - '#ffffff'
    - '#7f99cd'
    - '#d6e1f0'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
