typography_spectrum: 0.89357
color:
  brandColors:
    - '#005daa'
    - '#b9c5e4'
    - '#ffffff'
    - '#7f99cd'
    - '#d6e1f0'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05153841967694461
analytics:
  google: null
  facebook: null
  twitter: null
name: thePRguy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'http://theprguy.com/about/theprguys-history-brief'
    type: external
  - name: Credentials
    url: 'http://theprguy.com/about/about-david-kirk-apr-fellow-prsa'
    type: external
  - name: Accreditation
    url: 'http://theprguy.com/about/accreditation-public-relations'
    type: external
favicon: null
title: Building Better Relationships Through Effective Communication
purpose: []
