name: thePRguy
favicon: null
layout_spectrum: 0.05153841967694461
typography_spectrum: 0.8036658670753241
title: Building Better Relationships Through Effective Communication
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.387858712580055
  lightness: 0.3687714049592614
  saturation: 0.44419774203561246
  rhythmicContrast: 0.6651676737237722
purpose: []
